services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    image: "${API_SANDBOX_IMAGE_NAME}:${API_SANDBOX_IMAGE_TAG}"
    container_name: "${API_SANDBOX_IMAGE_NAME}"
    volumes:
      - ./workspaces:/workspaces
    working_dir: /workspaces
    healthcheck:
      test: ["CMD", "echo", "Hello ManasAI Gang!"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: tail -f /dev/null
